// Code generated by ogen, DO NOT EDIT.

package ping

import (
	"github.com/go-faster/jx"

	std "encoding/json"
	"testing"

	"github.com/stretchr/testify/require"
)

func TestPong_EncodeDecode(t *testing.T) {
	var typ Pong
	typ.SetFake()

	e := jx.Encoder{}
	typ.Encode(&e)
	data := e.Bytes()
	require.True(t, std.Valid(data), "Encoded: %s", data)

	var typ2 Pong
	require.NoError(t, typ2.Decode(jx.DecodeBytes(data)))
}
