// Code generated by ogen, DO NOT EDIT.

package ping

// Ref: #/components/schemas/Pong
type Pong struct {
	Ping string `json:"ping"`
}

// GetPing returns the value of Ping.
func (s *Pong) GetPing() string {
	return s.Ping
}

// SetPing sets the value of Ping.
func (s *Pong) SetPing(val string) {
	s.Ping = val
}
